---
engines:
  csslint:
    enabled: true
  scss-lint:
    enabled: true
    checks:
      ImportantRule:
        enabled: false
      StringQuotes:
        enabled: false
      VendorPrefix:
        enabled: false
      IdSelector:
        enabled: false
      DuplicateProperty:
        enabled: false
      SingleLinePerSelector:
        enabled: false
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.scss"
  - "**.sass"
exclude_paths:
- "/dev/static/sass/vendor/"
- "/dev/static/js/vendor/"
